# Devnet-2 environment
environment: devnet

chain:
  chain_id: moca_5151-1
  rpc: https://tm-rpc.devnet-2.mocachain.dev
  grpc: grpc.devnet-2.mocachain.dev:443
  rest: https://lcd.devnet-2.mocachain.dev
