# Mainnet environment (smoke tests only)
environment: mainnet

chain:
  chain_id: moca_2288-1
  rpc: https://tm-rpc.mocachain.dev
  grpc: grpc.mocachain.dev:443
  rest: https://lcd.mocachain.dev

readonly: true
