# Testnet environment
environment: testnet

chain:
  chain_id: moca_222888-1
  rpc: https://testnet-lcd.mocachain.org:443
  api: https://testnet-api.mocachain.org
  rest: https://testnet-api.mocachain.org
  evm_rpc: https://testnet-rpc.mocachain.org
